### ISSUE TITLE
Nether Tracking Broken

### ISSUE THREAD

**Issue by Bobmarlinjr** [NateKomodo/DreamManHunt#14]
Idk if the plugin is supposed to track the speedrunner with the compass in the nether, but it doesnt seem to cooperate. I am running a spigot server 1.16.

**Comment by NateKomodo** [comment]
Can you provide more information? What you expect it to do, what it is doing, your config, etc

**Comment by Bobmarlinjr** [comment]
The compass needle is not pointing towards a speedrunner in the nether, it just kind of moves around randomly. Its not spinning wildly as it would when the speedrunner is in another world. The tracking works perfectly in the overworld. Here is my config:

Compass tracking: true
compass-give: true
Compass particle: false
Nether particle: false
different worlds: true
freeze: false
insta kill: false

**Comment by NateKomodo** [comment]
from https://minecraft.gamepedia.com/Compass#Usage
`In the Nether or the End, the compass' needle spins and points in random directions. `
So this is working as expected. If you want to track in nether, use the particle options
