### ISSUE TITLE
Suggestion: portal tracking

### ISSUE THREAD

**Issue by KirbyKareem** [NateKomodo/DreamManHunt#16]
When the speedrunner goes through a portal, it should save their last coordinates in that dimension. Would be very helpful for the hunters and would make the compass perfect for my needs :D

**Comment by NateKomodo** [comment]
going to leave this up for grabs to anyone that wants to contribute for the time being as i am currently too busy to work on this

**Comment by RobinRMC** [comment]
Make it configurable, but disabled by default.

**Comment by NateKomodo** [comment]
#27 adds this feature as well as the config values, but it looks like it hasnt been touched. Might just merge it anyway as the codebase looks fine

**Comment by NateKomodo** [comment]
Implemented via #27

**Comment by NateKomodo** [comment]
I will push out a build later. In the meantime you can clone master and build it yourself by following the build instructions
