### ISSUE TITLE
Doesnt give compass on death sometimes

### ISSUE THREAD

**Issue by MinecraftMan1013number2** [NateKomodo/DreamManHunt#18]
## Some information
Operating system: Windows 10
Java version: 8
Minecraft version: 1.16.4

## Exception, error or logs
Please find your `latest.log` attach it to the issue
no errors in there (nothing at all in there related to glitch)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
add 1 speed runner and assassin
speed runner kill assassin

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have filled in all the sections.
- [x] I have included logs, exceptions and / or steps to reproduce the issue.

**Comment by MinecraftMan1013number2** [comment]
I think it might be because when the assassin dies, it removes them from the assassin group.

**Comment by NateKomodo** [comment]
> I think it might be because when the assassin dies, it removes them from the assassin group.

it doesnt, in fact there is no event for player death. There is an event for player respawn, but that doesnt mess with roles

i will look into this

**Comment by MinecraftMan1013number2** [comment]
Not to be rude, I believe that there is an on death event. I use Skript (idk if its called death event), and you can do this
`on death:`
` <tab>if victim is a player:`
` <tab> <tab># code`

**Comment by NateKomodo** [comment]
> Not to be rude, I believe that there is an on death event. I use Skript (idk if its called death event), and you can do this
> `on death:`
> ` \tif victim is a player:`
> `\t\t# code`

no i mean the plugin doesnt use the death event

**Comment by MinecraftMan1013number2** [comment]
> > Not to be rude, I believe that there is an on death event. I use Skript (idk if its called death event), and you can do this
> > `on death:`
> > ` \tif victim is a player:`
> > `\t\t# code`
> 
> no i mean the plugin doesnt use the death event

maybe you could add a section for that. Also (unrelated) why do you use UUIDs instead of just player name?

**Comment by NateKomodo** [comment]
> maybe you could add a section for that

Not sure what you mean by that

> why do you use UUIDs instead of just player name?

UUIDs are fixed & wont change, its good practice to use them over names

**Comment by MinecraftMan1013number2** [comment]
> > maybe you could add a section for that
> 
> Not sure what you mean by that
> 
> > why do you use UUIDs instead of just player name?
> 
> UUIDs are fixed & wont change, its good practice to use them over names

but for something temporary (like who is the assassin and who is the speedrunner), i think it would be better to use just their names. it makes the list of assassins and speedrunners kinda useless

**Comment by MinecraftMan1013number2** [comment]
> > maybe you could add a section for that
> 
> Not sure what you mean by that

like a new class or something that removes them then adds them back (so they get the compass)

**Comment by NateKomodo** [comment]
> > > maybe you could add a section for that
> > 
> > 
> > Not sure what you mean by that
> 
> like a new class or something that removes them then adds them back (so they get the compass)

Already thing using the respawn event (see original message) https://github.com/NateKomodo/DreamManHunt/blob/62148b8e75665ff289532c9d6e587eb820c25dcc/src/main/java/cloud/lagrange/assassin/event/Events.java#L78

**Comment by NateKomodo** [comment]
> > > maybe you could add a section for that
> > 
> > 
> > Not sure what you mean by that
> > > why do you use UUIDs instead of just player name?
> > 
> > 
> > UUIDs are fixed & wont change, its good practice to use them over names
> 
> but for something temporary (like who is the assassin and who is the speedrunner), i think it would be better to use just their names. it makes the list of assassins and speedrunners kinda useless

Again, good practices are to use uuids. Doesn't matter anyway as the new system just stores the player object by ref. 

Speaking of, if the command outputs UUIds for you, you are using an outdated version and should update

**Comment by MinecraftMan1013number2** [comment]
> > > > maybe you could add a section for that
> > > 
> > > 
> > > Not sure what you mean by that
> > > > why do you use UUIDs instead of just player name?
> > > 
> > > 
> > > UUIDs are fixed & wont change, its good practice to use them over names
> > 
> > 
> > but for something temporary (like who is the assassin and who is the speedrunner), i think it would be better to use just their names. it makes the list of assassins and speedrunners kinda useless
> 
> Again, good practices are to use uuids. Doesn't matter anyway as the new system just stores the player object by ref.
> 
> Speaking of, if the command outputs UUIds for you, you are using an outdated version and should update

I just downloaded it today

**Comment by NateKomodo** [comment]
> > > > > maybe you could add a section for that
> > > > 
> > > > 
> > > > Not sure what you mean by that
> > > > > why do you use UUIDs instead of just player name?
> > > > 
> > > > 
> > > > UUIDs are fixed & wont change, its good practice to use them over names
> > > 
> > > 
> > > but for something temporary (like who is the assassin and who is the speedrunner), i think it would be better to use just their names. it makes the list of assassins and speedrunners kinda useless
> > 
> > 
> > Again, good practices are to use uuids. Doesn't matter anyway as the new system just stores the player object by ref.
> > Speaking of, if the command outputs UUIds for you, you are using an outdated version and should update
> 
> I just downloaded it today

Try https://github.com/NateKomodo/DreamManHunt/releases/tag/v1.2.1

**Comment by MinecraftMan1013number2** [comment]
> > > > > > maybe you could add a section for that
> > > > > 
> > > > > 
> > > > > Not sure what you mean by that
> > > > > > why do you use UUIDs instead of just player name?
> > > > > 
> > > > > 
> > > > > UUIDs are fixed & wont change, its good practice to use them over names
> > > > 
> > > > 
> > > > but for something temporary (like who is the assassin and who is the speedrunner), i think it would be better to use just their names. it makes the list of assassins and speedrunners kinda useless
> > > 
> > > 
> > > Again, good practices are to use uuids. Doesn't matter anyway as the new system just stores the player object by ref.
> > > Speaking of, if the command outputs UUIds for you, you are using an outdated version and should update
> > 
> > 
> > I just downloaded it today
> 
> Try https://github.com/NateKomodo/DreamManHunt/releases/tag/v1.2.1

i have ver 1.2.1

**Comment by NateKomodo** [comment]
> > > > > > > maybe you could add a section for that
> > > > > > 
> > > > > > 
> > > > > > Not sure what you mean by that
> > > > > > > why do you use UUIDs instead of just player name?
> > > > > > 
> > > > > > 
> > > > > > UUIDs are fixed & wont change, its good practice to use them over names
> > > > > 
> > > > > 
> > > > > but for something temporary (like who is the assassin and who is the speedrunner), i think it would be better to use just their names. it makes the list of assassins and speedrunners kinda useless
> > > > 
> > > > 
> > > > Again, good practices are to use uuids. Doesn't matter anyway as the new system just stores the player object by ref.
> > > > Speaking of, if the command outputs UUIds for you, you are using an outdated version and should update
> > > 
> > > 
> > > I just downloaded it today
> > 
> > 
> > Try https://github.com/NateKomodo/DreamManHunt/releases/tag/v1.2.1
> 
> i have ver 1.2.1

1.2.1 or 1.2.1-release? There are two distinct because of a versioning mistake. The manhunt command should only output names and not UUIDs

**Comment by NateKomodo** [comment]
Stale issue and unable to recreate
