### ISSUE TITLE
How do I automatically regenerate/reset the world for a new game?

### ISSUE THREAD

**Issue by WalrusSlayer** [NateKomodo/DreamManHunt#24]
Hello, how can this be done? 

I need it to be fully automated.

Thanks!

**Comment by NateKomodo** [comment]
Write a plugin (or fork this repo and add your own code to it if you need access to roles, events, and config) that deletes the world and generates a new one via the bukkit API.

This isnt really an issue to do with the manhunt plugin so i am going to close this issue. You are free to keep asking questions here though
