### ISSUE TITLE
How to config

### ISSUE THREAD

**Issue by DreamBlade12345** [NateKomodo/DreamManHunt#25]
You should make it more obvious on how to config. I am still unsure on how to, so if you could help me, that would be great!

**Comment by NateKomodo** [comment]
[Its in the readme](https://github.com/NateKomodo/DreamManHunt#config)

Just open up the config.yml in a text editor like you would for any other plugin

**Comment by DreamBlade12345** [comment]
Will this change it for everyone or just me?

**Comment by NateKomodo** [comment]
I'm not sure what you mean by that, its a config for how the plugin behaves? A description of what each thing does is in the readme
