### ISSUE TITLE
Question about config.yml

### ISSUE THREAD

**Issue by DreamBlade12345** [NateKomodo/DreamManHunt#26]
When under DreamManHunt/src/main/resources/config.yml , would it change it for just me, or everyone?

**Comment by NateKomodo** [comment]
You are modifying the code for the plugin. You do not need to do that. Go into your plugins folder in your server, open the "assassin" folder, and open config.yml in a text editor

**Comment by NateKomodo** [comment]
Please do not make multiple issues for the same thing. You can still reply to closed issues.

**Comment by DreamBlade12345** [comment]
Oh, ok. Sorry about that.
