### ISSUE TITLE
Instalation issue

### ISSUE THREAD

**Issue by LifelessLizard** [NateKomodo/DreamManHunt#6]
I can't install it on a server. I use minehut as a server host but I can't put a jar file in the skript plugin.

Please help me as soon as posseble.

**Comment by NateKomodo** [comment]
I'm not sure what you mean by "I can't put a jar file in the skript plugin." This isn't a skript plugin, you just put the jar file in the plugins folder in your server directory.

**Comment by LifelessLizard** [comment]
Oh, sorry im stupid. Thank you!
