### ISSUE TITLE
/assassin to get Debug info lists UUID rather than player names

### ISSUE THREAD

**Issue by 28531** [NateKomodo/DreamManHunt#9]
![image](https://user-images.githubusercontent.com/26316049/88012358-8a43e300-cace-11ea-9881-c837fa5e24bf.png)

While very minimal, I was wondering if there was an option that would allow me to get player names rather than the UUID of players. Thanks

**Comment by NateKomodo** [comment]
The debug list was made to test the functionality of the role tracker. It simply outputs the contents of https://github.com/NateKomodo/DreamManHunt/blob/53d678c2e1a7738084410eb729778e21b2eaeafb/src/main/java/cloud/lagrange/assassin/Global.java#L8 which contains UUIDs and role. It was never inteded for non-debug use.
